INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(1, 'user', 'Usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(2, 'password', 'Contraseña', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(3, 'login', 'Ingresar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(4, 'locale_code', 'es', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(5, 'date_format_long', '%d de %B de %Y', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(6, 'site_header_title', 'GDR', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(7, 'site_header_motto', 'Gestión de reclamos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(8, 'document', 'Documento', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(9, 'upload', 'Subir', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(10, 'maxuploadfilesize', 'Tamaño máximo de archivo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(11, 'origin', 'Origen', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(12, 'origincau', 'CAU', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(13, 'originteleprom', 'Teleprom', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(14, 'complete_mandatory_fields', 'Complete los campos obligatorios', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(15, 'error', 'Error', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(16, 'back', 'Volver', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(17, 'import', 'Importar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(18, 'no_results_found', 'No se encontraron resultados', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(19, 'filters', 'Filtros', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(20, 'filter_apply', 'Aplicar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(21, 'clear', 'Limpiar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(22, 'date_format', 'd/m/Y', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(23, 'next', 'Siguente', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(24, 'previous', 'Anterior', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(25, 'export', 'Exportar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(26, 'date_between', 'Fecha entre', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(27, 'date_format_js', 'dd/mm/yy', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(28, 'state', 'Estado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(29, 'select_an_option', 'Seleccione una opción', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(30, 'pending', 'Pendiente', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(31, 'closed', 'Cerrado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(32, 'cancelled', 'Baja', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(33, 'cancel_claims', 'Dar de baja', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(34, 'error_field_max_length', 'El valor del campo excede el máximo de caracteres permitidos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(35, 'error_numeric_length', 'Debe ingresar sólo números', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(36, 'error_mail_format', 'Formato de e-mail incorrecto', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(37, 'phone_wrong_format', 'Formato de teléfono incorrecto', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(38, 'passwords_match_error', 'Las contraseñas no coinciden', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(39, 'logout', 'Salir', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(41, 'select_an_option', 'Seleccione...', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(42, 'select', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(40, 'origincauelectricity', 'Departamento de Electricidad', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(43, 'error_retrieving_geocode', 'Error al obtener geolocalización. Datos incorrectos o máximo de consultas diarias excedido.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(44, 'geolocate', 'Geolocalizar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(45, 'confirm', 'Confirmar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(46, 'select_location', 'Seleccionar localización', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(47, 'edit', 'Editar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(48, 'ok', 'OK', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(49, 'address', 'Dirección', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(50, 'lat', 'Lat', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(51, 'long', 'Long', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(54, 'map', 'Mapa', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(55, 'claims_map', 'Mapa de Reclamos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(56, 'print', 'Imprimir', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(57, 'stats', 'Estadísticas', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(58, 'close_claim_no_geo', 'Baja Sin Geo Referenciar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(59, 'close_claim_no_geo_short', 'Baja S/Geo.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(60, 'close_claim', 'Cerrar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(61, 'closed_no_geo', 'Baja sin georeferencia', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(62, 'requester_phone', 'Teléfono', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(63, 'claim_code', 'ID', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(64, 'total_users', 'Total', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(65, 'user_id', 'ID', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(66, 'user_actions', 'Acciones', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(67, 'user_edit', 'Editar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(68, 'user_delete', 'Eliminar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(69, 'new_user', 'Nuevo Usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(70, 'user_firstname', 'Nombre', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(71, 'user_lastname', 'Apellido', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(72, 'user_loggin', 'Usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(73, 'user_password', 'Contraseña', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(74, 'user_confirm_password', 'Confirmar Contraseña', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(75, 'user_phone_number', 'Teléfono', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(76, 'adr_plan_name', 'Empresa', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(77, 'adr_plan_name_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(78, 'user_save', 'Guardar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(79, 'user_fullname', 'Nombre y Apellido', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(80, 'user_state', 'Estado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(81, 'user_state_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(82, 'user_phone_company', 'Compañía Telefónica', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(83, 'user_cancel_save', 'Cancelar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(84, 'plan_name', 'Nombre', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(86, 'plan_coordinateupdatetime', 'Frecuencia Envío de Coordenadas', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(87, 'plan_save', 'Guardar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(88, 'plan_cancel_save', 'Cancelar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(89, 'plan_id', 'Id', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(90, 'new_plan', 'Nueva Empresa', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(91, 'plan_edit', 'Editar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(92, 'plan_delete', 'Eliminar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(93, 'plan_actions', 'Acciones', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(94, 'total_plans', 'Total', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(95, 'plan_claimattendedtime', 'Tiempo de Respuesta a Reclamo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(96, 'error_url_format', 'Debe ingresar una url válida', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(97, 'plan_coordinateupdatetime_short', 'Frec. Env. Coord.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(98, 'plan_minutestoclose_short', 'Tmp. Resp. Rec.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(99, 'password_length_error', 'La contraseña es muy corta', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(100, 'user_phone_company_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(101, 'adr_claims_track_select_one', 'Buscar usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(102, 'adr_claims_track_users_history', 'Historial de usuarios', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(103, 'adr_claims_track_assign_tasks', 'Asignar tareas', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(104, 'adr_claims_track_search_claim', 'Buscar reclamos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(105, 'adr_claims_track_hour_from', 'Desde hora', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(106, 'adr_claims_track_hour_to', 'Hasta hora', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(107, 'adr_claims_track_search_address', 'Buscar dirección', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(108, 'adr_claims_track_date_from', 'Desde', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(109, 'adr_claims_track_date_to', 'Hasta', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(110, 'adr_claims_track_states_select', 'Tipo de reclamo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(111, 'adr_claims_latitude_error', 'Error al obtener la latitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(112, 'adr_claims_longitude_error', 'Error al obtener la longitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(113, 'adr_users_get_user_error', 'Error al obtener los usuarios adr', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(114, 'adr_claim_track_clean_filters', 'Limpiar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(115, 'adr_claim_track_apply_filters', 'Aplicar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(116, 'adr_claims_track_user_title', 'Usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(117, 'adr_claims_track_claims_title', 'Reclamos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(118, 'adr_claims_address_title', 'Dirección', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(119, 'adr_claims_track_assign_tasks_title', 'Asignar tareas', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(120, 'adr_claims_track_assign_tasks_list_title', 'TAREAS', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(121, 'adr_claims_track_assign_tasks_list_id', 'ID', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(122, 'adr_claims_track_assign_tasks_list_address', 'DIRECCION', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(123, 'adr_claims_track_assign_tasks_submit', 'Guardar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(124, 'error_retrieving_data', 'Error al recuperar datos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(125, 'adr_claims_track_reset_plygon', 'Borrar polígono', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(126, 'plan_latitude', 'Latitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(127, 'plan_longitude', 'Longitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(128, 'adr_claims_track_timer', 'Seguimiento continuo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(129, 'adr_claims_track_requester_name', 'Solicitante', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(130, 'adr_claims_track_requester_address', 'Dirección solicitante', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(131, 'adr_claims_track_closed_date', 'Fecha de cierre', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(132, 'claims_get_code_error', 'Error al obtener id de reclamo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(133, 'adr_assign_tasks_assign_ok', 'La asignación se realizó satisfactoriamente.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(134, 'assign_claims', 'Asignar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(135, 'assign_claims_error', 'Error al asignar reclamos', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(136, 'adr_claims_track_generate_route', 'Generar ruta', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(137, 'adr_claims_track_optimize_route', 'Optimizar ruta', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(138, 'plan_coordinateupdatetime_short_unit', 'seg.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(139, 'plan_minutestoclose_short_unit', 'min.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(140, 'adr_claims_track_entry_date', 'Fecha de ingreso', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(141, 'error_loggin_username_exists', 'El nombre de usuario ya existe en el sistema', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(142, 'error_loggin_username_check', 'Error al verificar el nombre de usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(143, 'confirm_delete_systemuser', 'Realmente desea eliminar este usuario?', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(144, 'error_delete_systemuser', 'Error al eliminar el usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(145, 'error_saving_systemuser', 'Error al guardar el usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(146, 'error_saving_company', 'Error al guardar empresa', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(147, 'confirm_delete_company', 'Realmente desea eliminar esta empresa?', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(148, 'error_delete_company', 'Error al eliminar el plan', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(149, 'error_select_systemuser', 'Debe seleccionar un usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(150, 'caption_pending_claim_critic', 'Reclamo pendiente crítico', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(151, 'caption_pending_claim', 'Reclamo pendiente', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(152, 'caption_canceled_claim', 'Reclamo dado de baja', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(153, 'caption_closed_claim', 'Reclamo cerrado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(154, 'caption_user_connected', 'Usuario conectado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(155, 'caption_user_disconnected', 'Usuario desconectado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(156, 'caption_company', 'Empresa', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(157, 'caption_assigned_claim', 'Reclamo asignado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(158, 'caption_user', 'Usuario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(159, 'adr_captions_box', 'Leyenda', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(160, 'show_calendar', 'Mostrar calendario', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(161, 'adr_track_default_days', '30', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(162, 'adr_users_history_date_time', 'Fecha y hora', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(163, 'plan_minutesforcancellation_short', 'Tmp. Cancel. Rec.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(164, 'plan_minutesforcancellation_short_unit', 'min.', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(165, 'zone_name', 'Nombre zona', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(166, 'event_name', 'Evento', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(167, 'event_date', 'Fecha y hora', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(168, 'error_retrieving_claims_data', 'No se han obtenido reclamos sin asignar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(169, 'event_time_in', 'Hora entrada', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(170, 'event_time_out', 'Hora salida', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(171, 'time_in_zone', 'Tiempo en zona', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(172, 'caption_user_online', 'Usuario conectado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(173, 'caption_user_offline', 'Usuario desconectado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(174, 'results_found', 'registros encontrados', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(175, 'caption_user_path', 'Puntos visitados', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(176, 'entry_date', 'Fecha de ingreso', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(177, 'subject_name', 'Tema', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(178, 'input_type_name', 'Ingreso', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(179, 'cause_name', 'Motivo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(180, 'dependency', 'Dependencia', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(181, 'requester_name', 'Solicitante', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(182, 'claim_address', 'Domicilio', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(183, 'requester_phone', 'Teléfono', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(184, 'new_claim', 'Nuevo Reclamo', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(185, 'edit_claim', 'Editar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(186, 'claim_closed_date', 'Fecha de cierre', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(187, 'claim_assigned', 'Asignado', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(188, 'claim_latitude', 'Latitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(189, 'claim_longitude', 'Longitud', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(190, 'claim_neighborhood', 'Barrio', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(191, 'claim_piquete', 'Piquete', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(192, 'claim_region', 'Zona', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(193, 'claim_detail', 'Detalle', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(194, 'claim_save', 'Guardar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(195, 'claim_cancel_save', 'Cancelar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(196, 'claim_origin_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(197, 'claim_dependency_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(198, 'claim_state_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(199, 'claim_inputtype_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(200, 'claim_cause_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(201, 'manual', 'Manual', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(202, 'personal', 'Personal', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(203, 'telefonico', 'Telefónico', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(204, 'teleprom', 'Teleprom', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(205, 'claim_subject_select_one', 'Seleccionar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(206, 'confirm_map_accept', 'Aceptar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(207, 'confirm_map_cancel', 'Cancelar', 1);
INSERT INTO literal(id, lit_key, lit_text, lit_lang) VALUES(208, 'claim_geolocator', 'Cancelar', 1);
